### ISSUE TITLE
Can this extension be used on-prem Azure Devops Server

### ISSUE THREAD

**Issue by eliassal** [microsoft/security-devops-azdevops#100]
Hi, is it possible to use the extension localy, we have our on-prem Azure devops server and build agents on prem. If yes, how this can be installed and configured? Thanks

**Comment by charlesoxyer** [comment]
Hi @eliassal, currently our extension does not support on-prem ADO servers/on-prem build agents. This is on our backlog but currently not committed to on our roadmap, however I have documented this feature request for future iterations of planning.
