### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by eliassal** [microsoft/security-devops-azdevops#101]
If yes, can you please add setup instructions for on-Prem Azure Devops. Also, when I search the extensions market for 
Microsoft Defender for DevOps Container Mapping extension](https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.ms-dfd-code-to-cloud), it cant be found.

**Comment by charlesoxyer** [comment]
Hi @eliassal , this project is now part of Microsoft Defender for Cloud and additional documentation can be found here: https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-devops-introduction

For container image mapping: https://learn.microsoft.com/en-us/azure/defender-for-cloud/container-image-mapping

We do not currently support on-prem ADO servers.
