### ISSUE TITLE
Tasks show a warning on a stage in a pipeline

### ISSUE THREAD

**Issue by David-Mulder-at-VLK** [microsoft/security-devops-azdevops#103]
LS,
This extension has been installed by my organization, and on every stage in our Azure Devops yaml pipelines we now have two additional tasks: 
Microsoft Defender for DevOps Container Mapping Start
and
Microsoft Defender for DevOps Container Mapping End

The _end_ task show a warning in the summary from the pipeline run:
![image](https://github.com/microsoft/security-devops-azdevops/assets/144920223/4c53bdc8-a7c1-43db-a950-fcdeb2775c46)

However the actual task seems to run without an issue:
```
Starting: Microsoft Defender for DevOps Container Mapping End

Task         : Microsoft Security DevOps
Description  : Run the Microsoft Security DevOps CLI for static analysis.
Version      : 1.11.1
Author       : Microsoft Corporation
Help         : Runs the [Microsoft Security DevOps CLI](https://aka.ms/msdo-nuget) for security analysis. Effective September 20th 2023, the Secret Scanning option (CredScan) within Microsoft Security DevOps (MSDO) Extension for Azure DevOps is deprecated. MSDO Secret Scanning is replaced by the [Configure GitHub Advanced Security for Azure DevOps features](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features#set-up-secret-scanning) offering.

This task was injected as part of Microsoft Defender for DevOps enablement- https://go.microsoft.com/fwlink/?linkid=2231419
:::::
 Some Value 
Finishing: Microsoft Defender for DevOps Container Mapping End
```
Any insights on why this is?

**Comment by chrisnielsen-MS** [comment]
Thank you for reporting this @David-Mulder-at-VLK. These tasks are intended to identify any docker images/events that occur during the execution of your pipeline. I see now the logic handling the case where there are no docker events found is issuing a warning unnecessarily. We will address this in an upcoming release, thank you!

**Comment by chrisnielsen-MS** [comment]
This fix is now deployed and I am closing this issue. Please re-open or open a new issue if you see any further instances of this, thank you!
