### ISSUE TITLE
Task : Microsoft Security DevOps suddenly needs .net installation?

### ISSUE THREAD

**Issue by jaspervdstraten** [microsoft/security-devops-azdevops#105]
Hi all,

This error sudddenly started happening on friday/today. 

Starting: Microsoft Security DevOps
==============================================================================
Task         : Microsoft Security DevOps
Description  : Run the Microsoft Security DevOps CLI for static analysis.
Version      : 1.11.1
Author       : Microsoft Corporation
Help         : Runs the [Microsoft Security DevOps CLI](https://aka.ms/msdo-nuget) for security analysis. Effective September 20th 2023, the Secret Scanning option (CredScan) within Microsoft Security DevOps (MSDO) Extension for Azure DevOps is deprecated. MSDO Secret Scanning is replaced by the [Configure GitHub Advanced Security for Azure DevOps features](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features#set-up-secret-scanning) offering.
==============================================================================
------------------------------------------------------------------------------
Installing Microsoft Security DevOps Cli version: Latest
Microsoft.Security.Devops.Cli.linux-x64 version 0.200.1 already installed
------------------------------------------------------------------------------
**/workspace/_msdo/versions/Microsoft.Security.Devops.Cli.linux-x64.0.200.1/tools/guardian init --force
You must install .NET to run this application.**

App: /workspace/_msdo/versions/Microsoft.Security.Devops.Cli.linux-x64.0.200.1/tools/Microsoft.Guardian.Cli
Architecture: x64
App host version: 8.0.3
**.NET location: Not found**

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.3
/workspace/_msdo/versions/Microsoft.Security.Devops.Cli.linux-x64.0.200.1/tools/guardian run -p azuredevops --rich-exit-code --logger-pipeline --export-file /workspace/6/a/.gdn/msdo.sarif --telemetry-environment azdevops
You must install .NET to run this application.

App: /workspace/_msdo/versions/Microsoft.Security.Devops.Cli.linux-x64.0.200.1/tools/Microsoft.Guardian.Cli
Architecture: x64
App host version: 8.0.3
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

**Download the .NET runtime:**
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.3
##[error]MSDO CLI exited with an error exit code: 131
Finishing: Microsoft Security DevOps

**Comment by chrisnielsen-MS** [comment]
There was a regression in version 0.200.1 that caused this but it is now resolved in version 0.201.0

**Comment by jaspervdstraten** [comment]
Thanks @chrisnielsen-MS!
