### ISSUE TITLE
Trivy Image Scan not getting break when finding a MEDIUM or LOW vulnerability

### ISSUE THREAD

**Issue by SagarKalankar** [microsoft/security-devops-azdevops#113]
- While using Microsoft Security Devops Task for image scanning using Trivy tool, there are below environment variables which can be used:- 

- **GDN_RUN_MINSEVERITY**:- The name of the minimum severity log level to break on. Any results in this severity or ranked as more severe will cause a break. Default: Error

- **GDN_RUN_BREAKTOOL**:- A filter in the format toolName:severity that will restrict break to specified tools only. Any number of space-delimited tool:severity pairs may be specified.

- I wanted to fail my azure devops pipeline run if it finds a MEDIUM or LOW vulnerability. I tried using both environment variables with the MSDO task. But they are not working as expected.

Below is task how I used it:-    
    
<img width="384" alt="image" src="https://github.com/microsoft/security-devops-azdevops/assets/113438607/8f23519d-f254-4c61-b337-0f7bfbd4473d">

- The python image which is shown above contains LOW, MEDIUM, HIGH and CRITICAL severity vulnerabilities and I have set the 'GDN_RUN_MINSEVERITY' environment variable to MEDIUM but still the azure devops pipeline is not breaking in this task step.

- How can I make fail the pipeline when it finds the a LOW or MEDIUM severity vulnerability?
Documentations which I referred are given below:-

- Microsoft documentation link - https://learn.microsoft.com/en-us/azure/defender-for-cloud/azure-devops-extension

- Github env variables list documentation - https://github.com/microsoft/security-devops-azdevops/wiki#Trivy-options

**Comment by richardtucker** [comment]
I think the issues is that [Sarif](https://sarifweb.azurewebsites.net/) uses error, warning, note.
`GDN_RUN_MINSEVERITY: 'warning'` 
Should work for you. Please try that out and let me know. Thank you for the feedback; we will review the documentation and update it to make it clearer.

**Comment by SagarKalankar** [comment]
- I tried the way you said. Below is the task which I configured in the pipeline.
<img width="370" alt="image" src="https://github.com/microsoft/security-devops-azdevops/assets/113438607/3f537dfc-0972-4588-b13a-e9f15703fa05">

- The python image which is shown above contains MEDIUM, HIGH and CRITICAL severity vulnerabilities and I have set the 'GDN_RUN_MINSEVERITY' environment variable to 'warning'. When it is finding a MEDIUM vulnerability, then it is giving 'warning' which we can see in the pipeline task output but still the azure devops pipeline is not breaking in this task step.

<img width="702" alt="image" src="https://github.com/microsoft/security-devops-azdevops/assets/113438607/d00b98b8-6d0f-4e74-b222-74c7343b92a7">

- Can you please check why it is not breaking when finding MEDIUM or LOW severity?

**Comment by richardtucker** [comment]
I'm sorry to hear this did not address your current issue. To assist with troubleshooting, could you please provide a debug drop?
You can find more info about how to create one here: https://github.com/microsoft/security-devops-azdevops/wiki/Debug-Drops

**Comment by richardtucker** [comment]
Hopefully the logs helped solve your issue, please reopen and add debug drop if you still require assistance .
