### ISSUE TITLE
Terrascan results not publishing to Guardian

### ISSUE THREAD

**Issue by tnorwood001** [microsoft/security-devops-azdevops#118]
When running Terrascan against code, the policy finds violations which you can see in the log. When importing results into Guardian the log says "0 result file(s) created'.  Just above that line you can see the actual policy violations that Terrscan found in the code.

**Comment by chrisnielsen-MS** [comment]
Please share your log excerpts here and I can try to help interpret them. It is difficult to guess what the problem may be without the detailed logs to help explain.

**Comment by chrisnielsen-MS** [comment]
Closing this issue for lack of logs to investigate. Please re-open as needed.
