### ISSUE TITLE
Git the error message

### ISSUE THREAD

**Issue by edwardkuo** [microsoft/security-devops-azdevops#13]
I install this Extension. And use the Agent pool is azure pipeline. I don't finish to run it. I got these error message.
  BinSkim completed with exit code 1
##[error]Error running binskim job: 1 of 1
##[error]GuardianErrorExitCodeException: binskim completed with an Error exit code: 1. BinSkim failed. Verify the target(s) to be scanned. BinSkim targets must be a specific filename, or a pattern with a wildcard like *.dll, dir\*.dll, or dir\*
    ------------------------------------------------------------------------------
    
##[error]Error running tool 1 of 4: binskim
##[error]Error running binskim job: 1 of 1
##[error]GuardianErrorExitCodeException: binskim completed with an Error exit code: 1. BinSkim failed. Verify the target(s) to be scanned. BinSkim targets must be a specific filename, or a pattern with a wildcard like *.dll, dir\*.dll, or dir\*
##[error]MSDO CLI exited with an error exit code: 1

**Comment by lohithgn** [comment]
@edwardkuo 
when you use the task in your pipeline it is best practice to provide categories input. Categories are nothing but the analyzers you want to run when the task is executed in pipeline.
The categories available are: `secrets`, `code`, `artifacts`, `IaC`, `containers`. 
the categories input defaults to all & means it will run all analyzers available in the extension.
suggest you to understand what analyzer scans you need in your code base and mention them explicitly like below:
```
categories:secrets,code
```
the above input will let the extension execute secrets scan & code scan.
try it and let us know if this works fine.

**Comment by chrisnielsen-MS** [comment]
The guidance provided by @lohithgn covers this, closing the issue. @edwardkuo if you continue to have problems with your pipeline, feel free to re-open or create a new issue.

**Comment by edwardkuo** [comment]
Got, I will try it. thanks
