### ISSUE TITLE
Scan a specific path

### ISSUE THREAD

**Issue by pim-simons** [microsoft/security-devops-azdevops#16]
Currently the extension scans the entire git repo. 
It would be nice to be able to specify a specific path to scan as to not have to scan the entire repo on each pipeline run.

**Comment by flytzen** [comment]
Alternatively, to be able to exclude folders: ESLint, for example, finds warnings in the jQuery library.

**Comment by chrisnielsen-MS** [comment]
The tools often provide their own mechanism for exclusions. ESLint for example, can use an Exclusions File. You can see more information about configuring the tools using env variables in the wiki here: https://github.com/microsoft/security-devops-azdevops/wiki
