### ISSUE TITLE
Template Analyzer - Template / Validation Errors Cause Failure, no output to Sarif Scan Tab

### ISSUE THREAD

**Issue by rmazurik** [microsoft/security-devops-azdevops#22]
When working with the MSDO tool in our IaC Build Pipeline, we're experiencing an issue with our template : **Error exit code 22: 22. Violation + Error**

That is fine and understandable, but what's troubling is we're not able to view scan results in the Sarif Scan Tab, it seems the sarif files never get the chance to get loaded into the CodeAnalysisLogs artifact when this failure occurs. I'm wondering if this may be addressed in the code to allow for more meaningful error messages / remediation steps for these types of validation / error messages. to be displayed in this scans tab. Currently I'm having to sift through ~60,000 lines to find the error occurrence and it's hard to track down where in our files the failure is occurring.

![image](https://user-images.githubusercontent.com/107079616/204870611-a334ab9c-880b-4cbf-876b-35b9b36a5ec8.png)
![image](https://user-images.githubusercontent.com/107079616/204870514-663589eb-b67c-4103-bdd3-ffe115b6ce71.png)

**Comment by sivabalan-ammaiyappan** [comment]
I am also facing similar issue on the Build pipeline.
Error running templateanalyzer job: 1 of 1 
GuardianErrorExitCodeException: templateanalyzer completed with an Error exit code: 22. Violation + Error: Scan encountered both violations in template(s) and errors trying to analyze template(s)

**Comment by bjompen** [comment]
Same here with Binskim.
I have an exe file, [licecap.exe from cockos](https://www.cockos.com/licecap/), in my test / demo setup, and it fails binskim with error
```text
D:\a\1\s\DFDOFiles\licecap.exe : error ERR997.ExceptionLoadingPdb : 'licecap.exe' was not evaluated because its PDB could not be loaded (E_PDB_NO_DEBUG_INFO).

## <cut for brevity>
    ------------------------------------------------------------------------------
    BinSkim completed with exit code 1
##[error]Error running binskim job: 1 of 1
##[error]GuardianErrorExitCodeException: binskim completed with an Error exit code: 1. BinSkim failed. Verify the target(s) to be scanned. BinSkim targets must be a specific filename, or a pattern with a wildcard like *.dll, dir\*.dll, or dir\*
```

Adding an exclusion in .gdnconfig like this
```json
{
  "tools": [
    {
      "tool": {
        "name": "BinSkim",
        "version": "Latest"
      },
      "arguments": {
        "IgnorePdbLoadError": "true"
      }
    }
  ]
}
```
fixes the error and .sarif output is created

The tests do continue, and my log also has errors for other demo /test files, but the sarif output stops as soon as an error is output to the log.

**Comment by boAndron** [comment]
Fyi; a fix for Template Analyzer was deployed to deal with that issue. Also, a fix was deployed to prevent breaking the whole flow if a tool does not execute successfully. The exception will be caught and re-thrown at the end, after post-processing has completed.
