### ISSUE TITLE
Credscan: Support suppression in files that does not allow comments, such as JSON documents

### ISSUE THREAD

**Issue by eatsleepcodeplayrepeat** [microsoft/security-devops-azdevops#46]
There is no way of suppressing JSON documents as they do not support comments. Or I have not found documentation on how to use .gdnconfig for CredScan so suppress files.

**Comment by chrisnielsen-MS** [comment]
Hi @eatsleepcodeplayrepeat 

We plan to release a better user experience for suppressions in an upcoming release, but for now there are instructions on how you can do so early here: https://github.com/microsoft/security-devops-azdevops/issues/38#issuecomment-1509461347
