### ISSUE TITLE
Template analyzer Azure DevOps pipeline

### ISSUE THREAD

**Issue by wmayvis** [microsoft/security-devops-azdevops#47]
I got the following error:
##[error]ConfigurationPathNotFoundException: A configuration file could not be found for: template-analyzer. This is often due to attempting to use a tool on a platform where it is not yet supported.

![image](https://github.com/microsoft/security-devops-azdevops/assets/7701921/fb8982fb-6047-4564-a019-b9e022edce25)

![image](https://github.com/microsoft/security-devops-azdevops/assets/7701921/2b1c82a8-026a-45fa-b4b3-a41307729cd0)

**Comment by chrisnielsen-MS** [comment]
I think this is caused by the hyphen in the name. Please try using "templateanalyzer" in your yaml instead.

**Comment by wmayvis** [comment]
I've tried without the hyphen. The n I got object reference not set is null.....
