### ISSUE TITLE
[Q] How to configure suppressions file for CredScanner and use it?

### ISSUE THREAD

**Issue by VolodymyrMolodets** [microsoft/security-devops-azdevops#48]
Previously when using the Microsoft Security Code Analysis (MSCA) extension there was an option to specify the suppressions file path.
What would be the right way to use suppressions files in the Microsoft Security DevOps extension?

Unfortunately, the documentation over here https://github.com/microsoft/security-devops-action/wiki#how-to-configure-analyzers does not provide any examples.

This one https://learn.microsoft.com/en-us/azure/defender-for-cloud/detect-exposed-secrets#suppress-false-positives only suggests adding inline suppressions, but that's not a scalable and maintainable solution.

Looking forward for your suggestions.

**Comment by chrisnielsen-MS** [comment]
Hi! We plan to release a better user experience for this in an upcoming release, but for now you can configure this by following the instructions in this reply to another issue: https://github.com/microsoft/security-devops-azdevops/issues/38#issuecomment-1509461347
