### ISSUE TITLE
Trivy version is very out of date

### ISSUE THREAD

**Issue by dmakovec-astralas** [microsoft/security-devops-azdevops#50]
The tool currently uses Trivy v0.19.2, which is 2 years old. Can it please be updated to something more recent, current version being 0.41.0 ?

**Comment by boAndron** [comment]
An update to 0.38.1 is coming soon (next 2 weeks we hope), with more updates planned. Thanks!

**Comment by JamesChristianson** [comment]
The version is still out of date (v0.19.2). This is causing issues because apps using package-lock.json lockfileVersion: 3 , are not supported and vulnerabilities aren't found.
