### ISSUE TITLE
Pipeline Run Successful But Results not Visible

### ISSUE THREAD

**Issue by mlaraibkhan** [microsoft/security-devops-azdevops#60]
I ran this tool in my pipeline and have two methods to visualize results however none of them worked.

-  Published Artifacts:

<img width="181" alt="image" src="https://github.com/microsoft/security-devops-azdevops/assets/24682607/0d184e1c-4e78-4c2c-8048-0e6fbb4483c5">

- Using SARIF SAST Scans Tab -- Nothing to see (sc attached)

<img width="1004" alt="image" src="https://github.com/microsoft/security-devops-azdevops/assets/24682607/9d6cb5e5-ee3c-4de6-bc48-02f7d2be6ce3">

- Connecting Microsoft Defender for Cloud | DevOps security (preview) Azure Repos -- No visibility there as well.

![image](https://github.com/microsoft/security-devops-azdevops/assets/24682607/f7ded297-9dd3-441d-87fa-7e863d9a4227)

_Any suggestions?_

**Comment by chrisnielsen-MS** [comment]
Hello @mlaraibkhan, thank you for raising this support issue. Unfortunately, the Scans tab is not owned by Defender for DevOps and is a Microsoft DevLabs product. Our recommendation is to follow up with the Microsoft DevLabs team by providing direct feedback via the Azure DevOps Marketplace here: https://marketplace.visualstudio.com/items?itemName=sariftools.scans&ssr=false#qna

**Comment by chrisnielsen-MS** [comment]
Hi @mlaraibkhan,
Can you also confirm that the msdo.sarif file in your artifacts has any results in it? It may be that you are not seeing any results because the tools did not find any problems in your repositories.

**Comment by mlaraibkhan** [comment]
Hey,

I ran the test on a sample repository where I did find some issues, here's the sc, which indicates I have a few findings in msdo.sarif file.

<img width="1007" alt="image" src="https://github.com/microsoft/security-devops-azdevops/assets/24682607/f32e9369-4663-4389-9d1c-201644b37712">

**Comment by cajohanikea** [comment]
@chrisnielsen-MS I also have the same issue in one of our pipelines, the artifact uploaded includes the correct file but not visible.
If I create a " - task: PublishBuildArtifacts@1" the file is visible in the Scans section.

**Comment by chrisnielsen-MS** [comment]
Thank you for confirming @mlaraibkhan and thank you for the suggestion @cajohanikea -- @mlaraibkhan can you try adding the publish task and see if it shows up for you? If that still doesn't do it, I think following up with the Microsoft DevLabs team via my earlier link will be the best path forward.
