### ISSUE TITLE
Antimalware Scan not Supported on Linux Build Agents

### ISSUE THREAD

**Issue by rschmitzosi** [microsoft/security-devops-azdevops#71]
I'm testing out the anti-malware scan using the `ubuntu-latest` Azure pipeline image and finding that the error message says this is unsupported on Linux. Over in https://github.com/microsoft/security-devops-azdevops/pull/26, @sukhans mentioned that Linux should be working with all of the tools now, is that in fact the case or are some tools still unsupported? If the anti-malware scan is supported, are the pre-requisite steps required to get this functioning properly and could you please share them?

```
- task: MicrosoftSecurityDevOps@1
inputs:
  tools: 'antimalware'
```

```
##[error]ConfigurationPathNotFoundException: A configuration file could not be found for: antimalware-linux. This is often due to attempting to use a tool on a platform where it is not yet supported.
##[error]MSDO CLI exited with an error exit code: 1
Finishing: MicrosoftSecurityDevOps
```

**Comment by sukhans** [comment]
Apologies on the lack of clarity for this. Anti-Malware as a tool, was added at a later point and is currently available only for Windows. We do not have an ETA for a Linux version of it.
