### ISSUE TITLE
Slowness in task completion

### ISSUE THREAD

**Issue by Lddeiva** [microsoft/security-devops-azdevops#74]
The task seems to be taking lot of time recently. We are using self-hosted agent.

```YAML
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'
```

![image](https://github.com/microsoft/security-devops-azdevops/assets/61077834/8f113e89-aaff-4112-abbb-1ba25f8e5da7)

![image](https://github.com/microsoft/security-devops-azdevops/assets/61077834/277af083-02af-46c6-a766-f5663551efeb)

It used to be pretty fast earlier as shown below.

![image](https://github.com/microsoft/security-devops-azdevops/assets/61077834/b7f87c85-ad10-4cdf-963f-5997a41b8a3a)

**Comment by Lddeiva** [comment]
- The tasks should print the start time and end time so that it is easier to determine the time taken by each scanner.

**Comment by Lddeiva** [comment]
![image](https://github.com/microsoft/security-devops-azdevops/assets/61077834/2ff8d643-103d-4b53-bfde-ee500899f935)

![image](https://github.com/microsoft/security-devops-azdevops/assets/61077834/2dc92a98-4e8a-4825-b54f-ebb8955753ea)

![image](https://github.com/microsoft/security-devops-azdevops/assets/61077834/f387d132-34cf-4187-92ed-e7900e0de024)

![image](https://github.com/microsoft/security-devops-azdevops/assets/61077834/ace8b49f-6249-4fd1-b8eb-5232d0616d31)

@davidknise please find more information.

**Comment by dotpaul** [comment]
Hi @Lddeiva, just checking, have you seen this happening lately and if so, do you have raw logs with timestamps on each line?

**Comment by Lddeiva** [comment]
The task is working fine recently. Thank you @davidknise and @dotpaul .
