### ISSUE TITLE
Wrong paths for files in scan results with multi-checkouts. 

### ISSUE THREAD

**Issue by wooch82** [microsoft/security-devops-azdevops#75]
Regarding [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) each repo is checked out to a custom path $(Pipeline.Workspace)/s/_RepoName_ if use multi-checkouts.
In scans result section filenames have wrong links with _RepoName_
![image](https://github.com/microsoft/security-devops-azdevops/assets/56427350/d8d108cb-492f-4704-9de7-879b1d93645c)
so it causes the error I try to see the file in a repo:
![image](https://github.com/microsoft/security-devops-azdevops/assets/56427350/ef980ea5-15c5-47a2-bb28-0467407d16a8)

**Comment by MKippen** [comment]
Hello @wooch82, thank you for raising this support issue. Unfortunately, the Scans tab is not owned by Defender for DevOps and is a Microsoft DevLabs product. Our recommendation is to follow up with the Microsoft DevLabs team by providing direct feedback via the Azure DevOps Marketplace here: https://marketplace.visualstudio.com/items?itemName=sariftools.scans&ssr=false#qna
