### ISSUE TITLE
 SARIF SAST Scans Tab not showing scan results 

### ISSUE THREAD

**Issue by nsid123** [microsoft/security-devops-azdevops#89]
Hi I added Microsoft Security DevOps task and installed  SARIF SAST Scans Tab. I can see the artifacts that is getting generated with the extension msdo.sarif but i am not seeing any output in the Scans tab. It shows a blank page.

**Comment by dotpaul** [comment]
Hi @nsid123, I believe the SARIF SAST Scan Tabs is this repo: https://github.com/microsoft/sarif-azuredevops-extension/issues
